### ISSUE TITLE
Doesn't work for mac m1 vscode

### ISSUE THREAD

**Issue by rtsui-harmonicinc** [fwon/vscode-extension-pngquant#2]
Here is the log for the issue.
Cool work.

```log
Not found /Users/user/.vscode/extensions/fwon.pngquant-1.0.0/node_modules/node-pngquant-native/vendor/darwin-arm64-binding.node , You can rebuild it, to directory /Users/user/.vscode/extensions/fwon.pngquant-1.0.0/node_modules/node-pngquant-native,  Run `node-gyp rebuild` Command.
    at module.exports (/Users/user/.vscode/extensions/fwon.pngquant-1.0.0/node_modules/node-pngquant-native/scripts/binding.js:21:11)
    at Object.<anonymous> (/Users/user/.vscode/extensions/fwon.pngquant-1.0.0/node_modules/node-pngquant-native/index.js:2:46)
    at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:5647)
    at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:29431)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:35262)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at Module.require (/Users/user/.vscode/extensions/humao.rest-client-0.25.1/dist/extension.js:12:12993)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/user/.vscode/extensions/fwon.pngquant-1.0.0/extension.js:3:16)
    at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:5647)
    at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:29431)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:35262)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at Module.require (/Users/user/.vscode/extensions/humao.rest-client-0.25.1/dist/extension.js:12:12993)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:98)
    at h.vb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:30610)
    at async Promise.all (index 0)
```

**Comment by rtsui-harmonicinc** [comment]
```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0
```
